# Se necesita docker y docker-compose. Ejecutar con:
# docker-compose -f docker-compose.yml up
# Se iniciará un contenedor con postgresql y otro con odoo. 
# Para evitar conflictos con el puerto en local si ya hay postgres
# se usa el 5433 en lugar del estándar 5432 de postgresql.
---
version: '3.1'
services:
  db:
    image: postgres:9.6.5
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5433:5432"
    volumes:
      - data_storage:/var/lib/postgresql/data
  odoo12:
    container_name: odoo12
    depends_on:
      - db
    image: "rubencabrera/odoo-docker:12.0.4"
    ports:
      - "8169:8069"
      - "8171:8071"
      - "8172:8072"
    environment:
      - ADMIN_PASSWD=FIXME
      - DB_FILTER=False
    volumes:
      - odoo12_data:/var/lib/odoo
      - codigo:/opt
volumes:
  data_storage:
  odoo12_data:
  codigo:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/odoo-docker/opt    # This is where the code will live.
