language: bash
os: linux
sudo: required
services:
- docker
jobs:
  include:
  - stage: test
    script:
    - docker build -t "${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}" .
    - docker run  "${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}" /opt/odoo/odoo-bin --version
  - stage: release
    if: branch = semantic-release-2
    language: node_js
    node_js: '8'
    provider: script
    skip_cleanup: true
    script:
    - docker build -t "${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}" .
    - npm run semantic-release
env:
  global:
  - secure: K3NekWurK6+eL7qRh5tgb68zkr+pkdrixN9+Uxc118T1+ef3r2TFxZxIJ8m30hKUA3mPg2gqKe1DagMOlX1WsAO9ZlF/9Bqov0mf3Ft0B6pVgqN6VpTn+/0PTw6NdIEwxsGc35sSIhw0q/c51pIuiGLkLWzrNHnoVo8MO/WtJu/4bd24wnfJhea07OOzQnJyIkz2xzp9NdChbKSwJnEhsHVYRGDbctAe4KRg2tSruQge1uUzJFcXcUgd8sVCvH2QZS9eZyRzo1QfNnlZ1KJZAEV4U/lX7xlgYQPCGkSZvUmct++IZPsB3Sh5+p+tf6IfbGCOSf6ctVZzw+fv6YnWagGSShf1pKZJIBIX97EHC0gat92aUE+EtzIejFdA0jN61ztVIxL0y5rcWhwsIE9jVYJAxdDt3buxWCpsoIkxy5zz46S4OnOtPZEV8v9SJTrqJQi7f/7uWe0Dv8Ozjgk5CENSRhPd4JdiW8wxyFYr8HnHeuDu0GgN2dQ1v804veeBMQvkjJE8SXzKe1n/S5WNb7PxAGCrSLOheAAP3HfacU+zPWCbO3SGihjjSpxYdAZWfR0U7FwBVi5y2JSudvyN5M8/BoVv9/3xxRpjlhVkCQ9K283cmikHPcmYBgU6B4qp7IsO5dobFJt/oVxI3GYUYER5BRRnQKqw/imMfl3sKe8=
  - secure: S7j5k4IedJIX5akVg4Af1H4o2OJ/PC/4UMihXF2jHAejjOpNbJLtUdivVA/6a8c4gqydZohwogyjZ4f6wfIKyvKz+a4I4hS7bwrbihhtat6EtBaaLKbFqLeqmnorTu+PtvumjKUcvehgpUHpwDohDjjix2eTJ7qosRlZS0MYApac0KnObyDCF+vk99184d8aTl/WR6vgAqsNOz82QVPaK0cm/3DYQ2j9Dm5dglcFkqsGva/c3cdLdiBwdBM6shLUYcnZfttQWDS4Njtk8h9PLBDryyellrx95raugxVC/+ieh3f9KzqGF1m/i88VCwTlaXtB5LiTfApg4c4e4hj7qar6gLlSwPXrdh/w7DKa39akLnzSJKWelXcU2tsVyC1hYEJDpfpJZR43P9HSJ0DHBM9ZWH9sqeBZ5c2ZHGpq+AqU2FIUaO/LdPc3tToAQVpsucOppgjR6ph6rNEUVDGXNln/kW/Krb4Ti6hjNL/OTzCHQEH/eoQeA8Xc9m82AXf2cy5/ZWmrh0041Y/9P6QdwR4gJN4fOa8mR1DaAJyeyJf6FIAopHXbzuWcI6OPvASr6+2vv5s0mRrEQlyLtB+Z3ns8yZX20X0wQTmQXv+X/LgSjUdvFlymlfnSIEeKeFCeQFg4pEaXkDwayI3PD8iTJx+66qOBZF9D0jyg5u9uFMs=
  - secure: m1smjh5U+biTKITrX/rdwYZote1xHQ0HSsjrMvwiKvv6ZO9sDiy5g5xDvOiu72C5LveN+ufkxmcIDwFDvDkfxJuRsJ3VJeMgONfpHSdPUeTU3RdEOMTgHzaNnjBNTM8nsDwQCIQpXfZY3XZ6KccqRqQHyITdEtM4a02LdAA51b+3RJUQNvtlgWohbI/4ox33+niiwsxf8Wsf0c7TdA7IVy+8YzadGFIElCi93Scr49xMY1pLhQRzyIvX1t+oCfudiaSsvqJX3rcZcx8Pc+Jcype4A2UhWbSmXdEOuPyZGrFEaK8GV/fEl+dWfU9N6rtBHv9CHgTors7cNzFWB4D6+mTBrBYdNVxrXkcVbP3MEp4WwjH+e3H60f+cdmZ5qBzrmXFEYz3+WT5FJh9/a4OUr4IESGgXSQs7OJAfm4t1E7+FosokJ+fbJXtAkUHtQmbHr8NmZ1UFnD3RbfJqDUa/NLzDCSEXK4G4ElfiSL+JxfpjdFPtbCho7XVUXkCgbWJA/B5iM0xf1NOZeQr09dyivfqAqhgegtxfPAvLfN6fz5OfBTQOAtN54SGfXhszw9561OK/jkrb+GxfI3tndZrRSP9RrQeIXwpnvGJcjRVZ9FIYxVndMJkDrOxu7sLfO+xmhz9jXDEDbSb1YCRYRqyID32pnUswYc8z85H0SJQu2pY=
