language: bash
os: linux
sudo: required
env:
  global:
  - secure: yMjeyfyK8TGkoKtAZ5QAgdEB15fGPD18VwKoHJ8HBZJO80zGyemEgxeLDww5Rmr8nezfBddRtRfI7nq/W6HMxWJ0CUX6zpQ0pB9NqRhw0w1UCg2a8RuLfj6LJrPQNi55U9/VVPIrkrcvEoRb/yf6BkVAAc3ik9DNriMC0ojGXFodGACxK1jab0A/h3mSOuSQk2jwVcpZzVzkiF4F+LbCnIMiUBlclqU8bt9Pmx/wHRVs1UrTJSuyq+fuzIrvq0JOTZtAlWXmcId1nWFZmRTCVLthd/0L4jfFU8u9wlkIKD1c5oJHevKOMGCqPi8cNEYXoCij+b4UFv1QO8yR/iOVk1HmA9/KZf4AT1xRpTYWlziV6gt6B8nQmi65Ve871e/VbND7vpUvafzUV9cx36U3b4Gj9maItDUgbJ/VAFw8gRWBDXZRXedOu2jSpS3rWuBv649P522iC6+V6UZcSOeH4xriZvdWH1bGXNpDWgqMVKMFeIkW9j6x25YufPcWp8AInD0fsMG2nkBARkRTDFRJXiBD4qF4vv3lrw18dpRvEtOST5DPFrW+mk6OC5EfRntb9MYGgrdRaYqhlNKpmNjzhcUM+xmgOYrPOS3smdn+q9dtYJTUgzFemEUO2ynqpDnXvdoUoVZtiZvo/AUSgX1R1LS4j7/f9IwdFC099uz6qMU=
  - secure: OPKVfvbCfJ8evmaL6UxEK3AuNbyPTrfFV3OrMAV83k4wu7s3l357sHiXhTynxOoEVyv119ravDJcZQcpjA+2pZjRzn2tlDoFtAUEjcvKNZ57FjMasmVAxaQYTa1acVsrDPBfc4RCuWgZTKOGKmsT2a6lJ8AOMfYMMysIYjXUm0DMhXLQ+ctkCFyBFo6f1Mi/T+Tc61O0uOmt6n0iVIR5yzk9luUgi5w2Y2KCDc1j6B4H4GF2sK3pN4WORtlsvIElRu35n04ORYgAIqd2rOBKo8hyGtGhbozrQ96q49G8U4OLOsqNJ4nGopl3h6xPgJpkQqDWzzzATU1QPxxa3aKgfCh4kQMVnfTIh6j9UcBuJqbQSpuQ/KzoQ7VnwhA1UKvpJctqjk7xC23pp1RWrspo1Wni7cAsn1aFMKx024QMX5srKbYvAwkaxwqijaH6HhouMxiIzuinnVasGrpFt94BeIaE1ZlcNnFNVeur+4RBHeLlXlZTL5v4lCrgxv0nctdiK7vLYsukdA+2alOyQv0mPdPp6Up9J5YmzaWqAswZxKO5AhBIeqdeVbhzIIC3FzDMl7U1okbKh33dlV5K7Y8XFEm447x0uPGN+6U3q6N4bWT6Tsz0RQ+QadDdd2i5ySTzLjIvQhUI/QsobWa/I5d43hSZNGCtA42u3sforNEA0Bw=
  - secure: vdx1mCqxa/53E7wVfMW47dhSVycb/XuLNPvgOjVTmX4WQgMao6KQoC58GteIMDzREc7C2l5XAqdXaGGNU6h4gPuJrBDa2RWrmsyFzDK+MBs25DjnDJb3lPz2Fc6XoF0iKJ8jmnU4h7luQTdt2DxAEgbNv3bywreKVIr3ImGKZ19wxgP4QCnCsGGPQczuOxENdN+JTlx8uCePKjwPKpK0kVoOm87C8bRIwwZp1m5hgl+JwrBTLMUYkg/1Lz0TWM2cElrQayyIIyu8jz/HulRpJ70GL52QZ+4hm0TXFnw3To1g3ZQG5OMKc29Fdf/h3LQ7yei1cxS02SAMsvLSCUeF9KNk9IqwklBtcIJxZJVCz6oQ0ByQYvA/KbbvM9SjuDwBE3SOvuSe+K81goxB/sA1qYVRj6lCcpJypRT3z5+Zp2aShZXj5VQQL1Ncx/eUzjQ4xKM51lCQcuqPbmd5sFImfj39JUVLtu0s/RMeXa4TiumSOr2G5AD7yxt1ncr43HPoy3nWMpUlXtkWLmZYv8EMOysWd9pkDiPYpIB4OI3xCey/v/QC16ZjmoYx+MKC6QuN5L8Rm5N4DBbVxC+RL5l32ngBi1SYQPNgdSye1B4wLKdYW4mAdoL0bg1F5/0ICocRBHnxgJzinATIGFBUddot4L7LoL1keg2PO8d2bWntaPA=
services:
- docker
jobs:
  include:
  - stage: test
    script:
    - docker build -t "${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}" .
    - docker run  "${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}" /opt/odoo/odoo-bin --version
  - stage: release
    if: branch = semantic-release-2
    language: node_js
    node_js: '8'
    provider: script
    skip_cleanup: true
    script:
    - docker build -t "${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}" .
    - npm run semantic-release
