language: bash
os: linux
sudo: required
services:
- docker
jobs:
  include:
  - stage: test
    before_script:
    - docker build -t "${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}" .
    script:
    - docker run  "${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}" /opt/odoo/odoo-bin --version
  - stage: release
    if: branch = 12 OR branch = 12-dev
    language: node_js
    node_js: '8'
    provider: script
    skip_cleanup: true
    before_script:
    - "./.travis/release.bash"
    script:
    - nvm install lts/*
    - npx semantic-release
  - stage: deploy
    on:
      tags: true
    provider: script
    script:
    - "./.travis/docker_push.bash"
    skip_cleanup: true
