# docker and docker-compose are required. Run with:
# docker-compose -f docker-compose.yml up
# It will start a container with postgresql and another with odoo.
# To avoid conflicts with the local port if there is already postgres
# 5433 is used instead of the postgresql standard 5432.
---
version: '3.7'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    image: postgres:15
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - data_storage:/var/lib/postgresql/data
  odoo12:
    container_name: odoo16
    depends_on:
      - db
    image: "xyence/odoo-docker:16.0.0"
    ports: 
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    restart: always
    volumes:
      - odoo_data:/var/lib/odoo
volumes:
  # TODO: The local paths need to exist for volumes to be mounted
  data_storage:
  odoo_data:
