# Se necesita docker y docker-compose. Ejecutar con:
# docker-compose -f docker-compose.yml up
# Se iniciará un contenedor con postgresql y otro con odoo. 
# Para evitar conflictos con el puerto en local si ya hay postgres
# se usa el 5433 en lugar del estándar 5432 de postgresql.
---
version: '3.1'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5433:5432"
    volumes:
      - data_storage:/var/lib/postgresql/data
  odoo10:
    container_name: praxya_odoo10
    depends_on:
      - db
    image: "praxya/odoo:10"
    ports: 
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    volumes:
      - odoo_data:/var/lib/odoo
volumes:
  data_storage:
  odoo_data:
